title: Network Cloud Security Engineer
author: ivandelgadilloz
email: j.ivan.df@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Topics about technology on networking, cloud, automation, security
show_excerpts: true # set to true to show excerpts on the homepage
remote_theme: samarsault/texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Ivan Delgadillo Fernandez
  tagline: Network Cloud Security Engineer
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false
  analytics_id: 'ivandelgadilloz'
  navigation:
    - title: Back to Home
      url: "/#"
    #- title: Resume
     # url: "/resume"

  # generate social links in footer
  social_links:
    github:  ivandelgadilloz
    linkedIn: in/ivandelgadilloz/
    linktr.ee: idelgadillo
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
